package User.view;

import User.beans.User;
import User.data.BdJDBC;
import java.util.List;

/**
 * @author gth
 * @projet TGT
 * @create 01/03/20
 * @modify 01/03/20 18:49
 * @version 1.0.0
 */
public class DListeUtilisateur extends javax.swing.JDialog {

    /**
     * Creates new form DListeUtilisateur
     */
    public DListeUtilisateur(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        BdJDBC data = new BdJDBC("root", "");
        data.loadDriver();
        data.connectionToDB(); 
        
        List<User> lt = data.getAllUtilisateur();
        User util = null; 
        int col = 6;
        int lig = lt.size();
        
        Object [][] listeUtil = new Object [lig][col]; 
        for (int i = 0; i < lig; i++) {
            util = lt.get(i);
            listeUtil[i][0] = util.getId();
            listeUtil[i][1] = util.getNom();
            listeUtil[i][2] = util.getPrenom();
            listeUtil[i][3] = util.getLogin();
            listeUtil[i][4] = util.getPwd();
            listeUtil[i][5] = util.getProfil();
        }
       
        tbListeUtilisateur.setModel(new javax.swing.table.DefaultTableModel(
            listeUtil,
            new String [] {
                "ID", "NOM", "PRENOM", "LOGIN", "PASSWORD", "PROFIL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
        };

    public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
    }
});
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbListeUtilisateur = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbListeUtilisateur.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        tbListeUtilisateur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOM", "PRENOM", "LOGIN", "PASSWORD", "PROFIL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbListeUtilisateur);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 904, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbListeUtilisateur;
    // End of variables declaration//GEN-END:variables
}
